# Generated by Django 4.2.4 on 2023-08-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evident_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
